### PR TITLE
Bump eslint-plugin-jest

### PR DESCRIPTION
**Pull request by MarkPolivchuk**
To avoid [issues](https://github.com/jest-community/eslint-plugin-jest/issues/270) in 22.6

### CODE REVIEW

**Comment by iansu** [comment]
I ran into this issue earlier but a new version hadn't been released yet. Have you tested this locally using yarn resolutions?

**Comment by MarkPolivchuk** [comment]
I symlinked this branch and re-ran yarn and it seemed to work.

**Comment by MarkPolivchuk** [comment]
Confirmed, eslint crashes using `eslint-plugin-jest@22.6.2`, `eslint-plugin-jest@22.7.0` does not.

**Comment by lorenzos** [comment]
Here, it crashes with `22.14.1`... Regression?

**Pull request merged**
